version: "3.9"
services:

  db:
    image: postgres:14-bullseye
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c 'flask --app main run --debug --host 0.0.0.0'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app

volumes:
  postgres_data:
