FROM python:3.11-buster

WORKDIR /tasks

COPY tasks/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY ./tasks /tasks

ENV PYTHONPATH=/tasks

# EXPOSE 80

# ENTRYPOINT ["/entrypoint."]

# Run the start script, it will check for an /app/prestart.sh script (e.g. for migrations)
# And then will start Gunicorn with Meinheld
# CMD ["/start.sh"]